services:
  api:
    build: .
    container_name: lyftr-api
    ports:
      - "8000:8000"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - data:/data

volumes:
  data:
